spring:
  application:
    name: monolith
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa.properties.hibernate:
    jdbc:
      batch_size: 1000
      batch_versioned_data: true
    order_updates: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/flight_atdd?useSSL=false&allowPublicKeyRetrieval=true&allowLoadLocalInfile=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: ${DB_USERNAME:fl_atdd}
    password: ${DB_PASSWORD:fl_atdd}

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none   # Disable auto schema creation to let Flyway handle it
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    org.flywaydb: DEBUG

todos:
  api:
    host: ${TODOS_API_HOST:https://jsonplaceholder.typicode.com}
